# : Manager [[[

[mgr]
cwd = { fg = "#e7e0e8" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff7385", bg = "#ff7385" }
marker_cut      = { fg = "#ffd9de", bg = "#ffd9de" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f2b7c1", bg = "#f2b7c1" }

# Count
count_copied   = { fg = "#321018", bg = "#ffd9de" }
count_cut      = { fg = "#321018", bg = "#ffd9de" }
count_selected = { fg = "#3c255a", bg = "#f2b7c1" }

# Border
border_symbol = "│"
border_style  = { fg = "#d8bafb" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#d8bafb", bold = true, bg = "#151218" }
inactive  = { fg = "#cfc1da", bg = "#151218" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#d8bafb", fg = "#3c255a", bold = true }
normal_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# Select mode
select_main = { bg = "#cfc1da", fg = "#352d40", bold = true }
select_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# Unset mode
unset_main = { bg = "#f2b7c1", fg = "#4b252d", bold = true }
unset_alt  = { bg = "#4a454e", fg = "#ccc4cf" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#8561a1" }
perm_write = { fg = "#db3551" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff4059" }
perm_sep   = { fg = "#a443ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#d8bafb", bg = "#3b383e" }
progress_error  = { fg = "#ffb4ab", bg = "#3b383e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b383e" }
cand = { fg = "#d8bafb" }
rest = { fg = "#3c255a" }
desc = { fg = "#e7e0e8" }
separator = " ▶ "
separator_style = { fg = "#e7e0e8" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#f2b7c1" }
title_warn  = { fg = "#d8bafb" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#d8bafb" }
active = { fg = "#f2b7c1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d8bafb" }
value  = { fg = "#e7e0e8" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#d8bafb", bg = "#3c255a" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#d8bafb" }
title   = {}
hovered = { fg = "#ffd9de", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e7e0e8" }
run    = { fg = "#e7e0e8" }
footer = { fg = "#352d40", bg = "#cfc1da" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e7e0e8" },
    { url = "*/", fg = "#d8bafb" },
]

# : ]]]
