# : Manager [[[

[mgr]
cwd = { fg = "#efe0d5" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#b8d066", bg = "#b8d066" }
marker_cut      = { fg = "#dce8b4", bg = "#dce8b4" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c0cc9a", bg = "#c0cc9a" }

# Count
count_copied   = { fg = "#161f01", bg = "#dce8b4" }
count_cut      = { fg = "#161f01", bg = "#dce8b4" }
count_selected = { fg = "#4a2800", bg = "#c0cc9a" }

# Border
border_symbol = "│"
border_style  = { fg = "#fcb975" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#fcb975", bold = true, bg = "#19120c" }
inactive  = { fg = "#e1c1a4", bg = "#19120c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#fcb975", fg = "#4a2800", bold = true }
normal_alt  = { bg = "#51453a", fg = "#d5c3b5" }

# Select mode
select_main = { bg = "#e1c1a4", fg = "#402c18", bold = true }
select_alt  = { bg = "#51453a", fg = "#d5c3b5" }

# Unset mode
unset_main = { bg = "#c0cc9a", fg = "#2a3410", bold = true }
unset_alt  = { bg = "#51453a", fg = "#d5c3b5" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#b1733b" }
perm_write = { fg = "#788845" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#a5c43f" }
perm_sep   = { fg = "#ff8a25" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#fcb975", bg = "#403830" }
progress_error  = { fg = "#ffb4ab", bg = "#403830" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#403830" }
cand = { fg = "#fcb975" }
rest = { fg = "#4a2800" }
desc = { fg = "#efe0d5" }
separator = " ▶ "
separator_style = { fg = "#efe0d5" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#c0cc9a" }
title_warn  = { fg = "#fcb975" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#fcb975" }
active = { fg = "#c0cc9a", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#fcb975" }
value  = { fg = "#efe0d5" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#fcb975", bg = "#4a2800" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#fcb975" }
title   = {}
hovered = { fg = "#dce8b4", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#efe0d5" }
run    = { fg = "#efe0d5" }
footer = { fg = "#402c18", bg = "#e1c1a4" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#efe0d5" },
    { url = "*/", fg = "#fcb975" },
]

# : ]]]
