# : Manager [[[

[mgr]
cwd = { fg = "#eedfe2" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff9f5e", bg = "#ff9f5e" }
marker_cut      = { fg = "#ffdcc4", bg = "#ffdcc4" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f1bc96", bg = "#f1bc96" }

# Count
count_copied   = { fg = "#2f1400", bg = "#ffdcc4" }
count_cut      = { fg = "#2f1400", bg = "#ffdcc4" }
count_selected = { fg = "#531d36", bg = "#f1bc96" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb0cd" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb0cd", bold = true, bg = "#191114" }
inactive  = { fg = "#e1bdc9", bg = "#191114" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb0cd", fg = "#531d36", bold = true }
normal_alt  = { bg = "#514347", fg = "#d5c2c7" }

# Select mode
select_main = { bg = "#e1bdc9", fg = "#412932", bold = true }
select_alt  = { bg = "#514347", fg = "#d5c2c7" }

# Unset mode
unset_main = { bg = "#f1bc96", fg = "#49290e", bold = true }
unset_alt  = { bg = "#514347", fg = "#d5c2c7" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#b15473" }
perm_write = { fg = "#d2681c" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff812b" }
perm_sep   = { fg = "#ff407c" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb0cd", bg = "#40373a" }
progress_error  = { fg = "#ffb4ab", bg = "#40373a" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#40373a" }
cand = { fg = "#ffb0cd" }
rest = { fg = "#531d36" }
desc = { fg = "#eedfe2" }
separator = " ▶ "
separator_style = { fg = "#eedfe2" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#f1bc96" }
title_warn  = { fg = "#ffb0cd" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb0cd" }
active = { fg = "#f1bc96", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb0cd" }
value  = { fg = "#eedfe2" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb0cd", bg = "#531d36" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb0cd" }
title   = {}
hovered = { fg = "#ffdcc4", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#eedfe2" }
run    = { fg = "#eedfe2" }
footer = { fg = "#412932", bg = "#e1bdc9" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#eedfe2" },
    { url = "*/", fg = "#ffb0cd" },
]

# : ]]]
