cursor            #d8bafb
cursor_text_color #3c255a

foreground            #e7e0e8
background            #100d12
selection_foreground  #352d40
selection_background  #cfc1da
url_color             #cfc1da

#: black 000000 767676
color0  #151218
color8  #373339
#: red cc0403 f2201f
color1  #503f6a
color9  #9c89b9
#: green 19cb00 23fd00
color2  #cfc1da
color10 #ebddf7
#: yellow cecb00 fffd00
color3  #f2b7c1
color11 #ffd9de
#: blue 0d73cc 1a8fff
color4  #533b72
color12 #d8bafb
#: magenta cb1ed1 fd28ff
color5  #4c4357
color13 #cfc1da
#: cyan 0dcdcd 14ffff
color6  #653b43
color14 #f2b7c1
#: white dddddd ffffff
color7  #ccc4cf
color15 #e7e0e8

mark1_foreground #260d44
mark1_background #eedcff
mark2_foreground #20182a
mark2_background #ebddf7
mark3_foreground #321018
mark3_background #ffd9de

active_tab_foreground #3c255a
active_tab_background #d8bafb
inactive_tab_foreground #eedcff
inactive_tab_background #533b72

active_border_color #d8bafb
inactive_border_color #3c255a
# bell_border_color #ff5a00
