cursor            #fcb975
cursor_text_color #4a2800

foreground            #efe0d5
background            #130d07
selection_foreground  #402c18
selection_background  #e1c1a4
url_color             #e1c1a4

#: black 000000 767676
color0  #19120c
color8  #3c332c
#: red cc0403 f2201f
color1  #364daf
color9  #7688d5
#: green 19cb00 23fd00
color2  #e1c1a4
color10 #ffdcbe
#: yellow cecb00 fffd00
color3  #c0cc9a
color11 #dce8b4
#: blue 0d73cc 1a8fff
color4  #693c00
color12 #fcb975
#: magenta cb1ed1 fd28ff
color5  #59422c
color13 #e1c1a4
#: cyan 0dcdcd 14ffff
color6  #414b24
color14 #c0cc9a
#: white dddddd ffffff
color7  #d5c3b5
color15 #efe0d5

mark1_foreground #2c1600
mark1_background #ffdcbe
mark2_foreground #291806
mark2_background #ffdcbe
mark3_foreground #161f01
mark3_background #dce8b4

active_tab_foreground #402c18
active_tab_background #e1c1a4
inactive_tab_foreground #ffdcbe
inactive_tab_background #693c00

active_border_color #fcb975
inactive_border_color #4a2800
# bell_border_color #ff5a00
